name       : rr
version    : 5.4.0
release    : 1
source     :
    - https://github.com/rr-debugger/rr/archive/refs/tags/5.4.0.tar.gz : ba3f604b76a1e917055efeac60c51148bcb578e64a55ceddad8b1a6f2740717e
license    : MIT
component  : programming.tools
summary    : rr is a lightweight tool for recording, replaying and debugging execution of applications
description: |
    rr is a lightweight tool for recording, replaying and debugging execution of applications (trees of processes and threads).
builddeps  :
    - pkgconfig(capnp)
    - gdb
    - python-pexpect
setup      : |
    %cmake_ninja -Ddisable32bit=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
