name       : rr
version    : 5.5.0
release    : 4
source     :
    - https://github.com/rr-debugger/rr/archive/refs/tags/5.5.0.tar.gz : b7d4d563cb8b4c4f1a2ca699b3759748570544f9e4526b8fd6f00febd1df723f
license    : MIT
component  : programming.tools
summary    : rr is a lightweight tool for recording, replaying and debugging execution of applications
description: |
    rr is a lightweight tool for recording, replaying and debugging execution of applications (trees of processes and threads).
builddeps  :
    - pkgconfig(capnp)
    - gdb
    - python-pexpect
setup      : |
    %cmake_ninja -Ddisable32bit=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
